name: practise workflow # name of workflow

on: 
  push   # trigger


jobs:
  FirstJob:     #1 job id(First job)
    name: Emmanuel
    runs-on: ubuntu-latest
    needs: SecondJob
    steps:
      - name: greetings   # identifier for step 1
        run:  echo "How are you learning"

      - name:  print all files  # identifier for step 2
        run:  ls -al

  SecondJob:
     runs-on: ubuntu-latest
     name: samuel
     

     steps: 
       - name: print my name
         run:   echo "Emmanuel"



     


        

  
  
    
  
